models/Movie.php
<?php

namespace app\models;

/**
 * This is the model class for table "movies".
 *
 * @property int $id
 * @property string $name
 * @property string $genre
 * @property string $country
 * @property string $duration
 * @property string $director
 * @property string|null $actors
 * @property string $release_date
 * @property string $description
 * @property int $status
 * @property string $images_path
 *
 * @property Show[] $shows
 */
class Movie extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'movies';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'genre', 'country', 'duration', 'director', 'release_date', 'description', 'status', 'images_path'], 'required'],
            [['description'], 'string'],
            [['status'], 'integer'],
            [['name', 'director'], 'string', 'max' => 45],
            [['genre', 'actors', 'images_path'], 'string', 'max' => 100],
            [['duration'], 'string', 'max' => 5],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Идентификатор',
            'name' => 'Название',
            'genre' => 'Жанр',
            'country' => 'Страна',
            'duration' => 'Длительность',
            'director' => 'Режиссер',
            'actors' => 'В ролях',
            'release_date' => 'Дата выхода',
            'description' => 'Описание',
            'status' => 'Статус',
            'images_path' => 'Путь к изображениям',
        ];
    }

    /**
     * Gets query for Shows.
     *
     * @return \yii\db\ActiveQuery
     */
    public function getShows()
    {
        return $this->hasMany(Show::class, ['movie_id' => 'id']);
    }

    /**
     * Возвращает кол-во записей
     *
     * @param array $params
     * @return int|string
     */
    public static function getCount($params = [])
    {
        return static::find()->where($params)->count();
    }
}

models/MovieForm.php
<?php

namespace app\models;

use yii\base\Model;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

class MovieForm extends Model
{
    /** @var integer|null  */
    public $id;
    /** @var string */
    public $name;
    /** @var string */
    public $oldName;
    /** @var string[] */
    public $genre;
    /** @var string[] */
    public $country;
    /** @var integer */
    public $hours;
    /** @var integer */
    public $minutes;
    /** @var string */
    public $director;
    /** @var string|null */
    public $actors;
    /** @var string */
    public $release_date;
    /** @var string */
    public $description;
    /** @var integer */
    public $status;
    /** @var UploadedFile */
    public $poster;
    /** @var UploadedFile[] */
    public $movie_shots;
    /** @var UploadedFile */
    public $trailer;

    public function __construct($config = [])
    {
        parent::__construct($config);
        if($this->id != null) {
            $this->fillFields($this->id);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'director', 'description', 'actors'], 'trim'],
            [['name', 'genre', 'country', 'hours', 'minutes', 'director', 'release_date', 'description'], 'required'],
            [['poster', 'movie_shots', 'trailer'], 'required', 'on' => 'create'],
            [['description'], 'string'],
            [['name', 'director'], 'string', 'max' => 45],
            [['actors'], 'string', 'max' => 100],
            [['status', 'hours', 'minutes'], 'integer'],
            [['poster'], 'image', /*'skipOnEmpty' => false,*/ 'extensions' => 'jpg', 'checkExtensionByMimeType'=>false],
            [['trailer'], 'file', /*'skipOnEmpty' => false,*/ 'extensions' => 'mp4', 'checkExtensionByMimeType'=>false],
            [['movie_shots'], 'image', /*'skipOnEmpty' => false,*/ 'extensions' => 'jpg', 'maxFiles' => 10, 'checkExtensionByMimeType'=>false],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Идентификатор',
            'name' => 'Название',
            'genre' => 'Жанр',
            'country' => 'Страна',
            'hours' => 'Часы',
            'minutes' => 'Минуты',
            'director' => 'Режиссер',
            'actors' => 'В ролях',
            'release_date' => 'Дата выхода',
            'description' => 'Описание',
            'status' => 'Статус',
            'poster' => 'Постер',
            'movie_shots' => 'Кадры из фильма',
            'trailer' => 'Трейлер'
        ];
    }

    /**
     * @return Movie|bool|null
     * @throws \yii\base\Exception
     */
    public function create()
    {
        if (!$this->validate()) {
            return false;
        }
        $movie = self::getMovie();

        $moviePath = 'images/movies/' . $this->transliterate($this->name) . '/';

        if (!file_exists($moviePath)) {
            FileHelper::createDirectory($moviePath . 'movie_shots');
        }

        $this->poster->saveAs($moviePath . 'poster.' . $this->poster->extension);
        $this->trailer->saveAs($moviePath . 'trailer.' . $this->trailer->extension);

        $movie->images_path = $moviePath;

        foreach ($this->movie_shots as $image) {
            $skip = false;
            while (!$skip) {
                $filename = uniqid();
                $imagePath = $moviePath . 'movie_shots/' . $filename . '.' . $image->extension;
                if (!file_exists($imagePath)) {
                    $skip = true;
                    $image->saveAs($imagePath);
                }
            }
        }

        return $movie->save() ? $movie : false;
    }

    /**
     * @return Movie|bool|null
     * @throws \yii\base\ErrorException
     * @throws \yii\base\Exception
     */
    public function update()
    {
        if (!$this->validate()) {
            return false;
        }

        $movie = self::getMovie();

        if ($this->name != $this->oldName) {
            $oldMoviePath = 'images/movies/' . $this->transliterate($this->oldName);
            $newMoviePath = 'images/movies/' . $this->transliterate($this->name);
            FileHelper::copyDirectory($oldMoviePath, $newMoviePath);
            FileHelper::removeDirectory($oldMoviePath);
        }

        if (!is_null($this->poster) || !is_null($this->movie_shots) || !is_null($this->trailer)) {
            $moviePath = 'images/movies/' . $this->transliterate($this->name) . '/';

            if (!file_exists($moviePath)) {
                FileHelper::createDirectory($moviePath . 'movie_shots');
            }
            if (!is_null($this->poster)) {
                $this->poster->saveAs($moviePath . 'poster.' . $this->poster->extension);
            }
            if (!is_null($this->trailer)) {
                $this->trailer->saveAs($moviePath . 'trailer.' . $this->trailer->extension);
            }
            $movie->images_path = $moviePath;

            if (!is_null($this->movie_shots)) {

                foreach ($this->movie_shots as $image) {
                    $skip = false;
                    while (!$skip) {
                        $filename = uniqid();
                        $imagePath = $moviePath . 'movie_shots/' . $filename . '.' . $image->extension;
                        if (!file_exists($imagePath)) {
                            $skip = true;
                            $image->saveAs($imagePath);
                        }
                    }
                }
            }
        }
        return $movie->save() ? $movie : false;
    }

    public function getPosterUrl()
    {
        return '/images/movies/' . $this->transliterate($this->name) . '/poster.jpg';
    }

    public function getMovieShotsUrl()
    {
        if (empty($this->name)) {
            return [];
        }
        $path = 'images/movies/' . $this->transliterate($this->name) . '/movie_shots';
        $files = FileHelper::findFiles($path);
        foreach ($files as $index => $file) {
            $files[$index] = '/' . $file;
        }

        return $files;
    }

    public function getPreviewConfig()
    {
        if (empty($this->name)) {
            return [];
        }
        $path = 'images/movies/' . $this->transliterate($this->name) . '/movie_shots';
        $files = FileHelper::findFiles($path);
        $result = [];
        foreach ($files as $file) {
            array_push($result, ['key' => $file]);
        }
        return $result;
    }

    public function getTrailerUrl()
    {
        return '/images/movies/' . $this->transliterate($this->name) . '/trailer.mp4';
    }

    /**
     * @return Movie|null
     */
    private function getMovie()
    {
        $movie = new Movie();
        if ($this->id) {
            $movie = Movie::findOne($this->id);
        }

        $movie->name = $this->name;

        $genres = '';
        foreach ($this->genre as $key => $genre) {
            $genres .= ($key == 0 ? '' : ', ') . $genre;
        }
        $movie->genre = $genres;

        $countries = '';
        foreach ($this->country as $key => $country) {
            $countries .= ($key == 0 ? '' : ', ') . $country;
        }
        $movie->country = $countries;

        if ($this->minutes < 10) {
            $this->minutes = '0' . $this->minutes;
        }

        $movie->duration = $this->hours . ':' . $this->minutes;
        $movie->director = $this->director;
        $movie->actors = $this->actors;
        $movie->release_date = $this->release_date;
        $movie->description = $this->description;
        $movie->status = $this->status;

        return $movie;
    }

    /**
     * Заполняет форму значениям из БД
     *
     * @param $id
     * @return $this
     */
    private function fillFields($id)
    {
        $movie = Movie::findOne($id);
        $this->name = $movie->name;
        $this->oldName = $movie->name;
        $this->genre = explode(', ', $movie->genre);
        $this->country = $movie->country;

        $duration = explode(':', $movie->duration);

        $this->hours = $duration[0];
        $this->minutes = $duration[1];
        $this->director = $movie->director;
        $this->description = $movie->description;
        $this->actors = $movie->actors;
        $this->release_date = $movie->release_date;
        $this->status = $movie->status;

        return $this;
    }

    private function transliterate($string) {
        $string = mb_strtolower($string);
        $converter  = array('а' => 'a', 'б' => 'b', 'в' => 'v', 'г' => 'g', 'д' => 'd', 'е' => 'e', 'ё' => 'e', 'ж' => 'zh', 'з' => 'z', 'и' => 'i', 'й' => 'y', 'к' => 'k', 'л' => 'l', 'м' => 'm', 'н' => 'n', 'о' => 'o', 'п' => 'p', 'р' => 'r', 'с' => 's', 'т' => 't', 'у' => 'u', 'ф' => 'f', 'х' => 'h', 'ц' => 'c', 'ч' => 'ch', 'ш' => 'sh', 'щ' => 'sch', 'ъ' => 'y', 'ы' => 'y', 'ь' => '', 'э' => 'e', 'ю' => 'yu', 'я' => 'ya', ' ' => '-');
        return strtr($string, $converter);
    }
}

controllers/MovieController.php
<?php

namespace app\controllers;

use Yii;
use app\models\MovieForm;
use app\models\Movie;
use app\models\MovieSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * MovieController implements the CRUD actions for Movie model.
 */
class MovieController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(){
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Movie models.
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->can('listMovies')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        $searchModel = new MovieSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Movie model.
     * @param integer $id
     * @return string
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        if (!Yii::$app->user->can('viewMovie')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * @return string|\yii\web\Response
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        if (!Yii::$app->user->can('createMovie')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        $model = new MovieForm(['scenario' => 'create']);

        if ($model->load(Yii::$app->request->post())) {
            $model->poster = UploadedFile::getInstance($model, 'poster');
            $model->movie_shots = UploadedFile::getInstances($model, 'movie_shots');
            $model->trailer = UploadedFile::getInstance($model, 'trailer');

            if ($movie = $model->create()) {
                Yii::$app->session->setFlash('success', 'Запись сохранена');
                return $this->redirect(['view', 'id' => $movie->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Movie model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return string|\yii\web\Response
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        if (!Yii::$app->user->can('updateMovie')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        $model = new MovieForm(['id' => $id]);

        if ($model->load(Yii::$app->request->post())) {
            $model->poster = UploadedFile::getInstance($model, 'poster');
            $model->movie_shots = UploadedFile::getInstances($model, 'movie_shots');
            $model->trailer = UploadedFile::getInstance($model, 'trailer');

            if ($model->update()) {
                Yii::$app->session->setFlash('success', 'Запись сохранена');
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete()
    {
        $filePath = Yii::$app->request->post('key');
        unlink($filePath);
        return '{}';
    }

    /**
     * Finds the Movie model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Movie the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Movie::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/movie/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use kartik\select2\Select2;
use kartik\file\FileInput;
use kartik\touchspin\TouchSpin;

/* @var $this yii\web\View */
/* @var $model app\models\MovieForm */
/* @var $form yii\widgets\ActiveForm */
/* @var $isUpdate boolean */

if (!isset($isUpdate)) {
    $isUpdate = false;
}
?>

<div class="movie-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'oldName')->hiddenInput()->label(false) ?>

    <?= $form->field($model, 'genre')->widget(Select2::class, [
        'name' => 'genre',
        'data' => \yii\helpers\ArrayHelper::map(\app\models\Genre::find()->all(), 'name', 'name'),
        'theme' => Select2::THEME_BOOTSTRAP,
        'options' => ['placeholder' => 'Выберите жанр', 'multiple' => true, 'autocomplete' => 'off'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]) ?>

    <?= $form->field($model, 'country')->widget(Select2::class, [
        'name' => 'country',
        'data' => \yii\helpers\ArrayHelper::map(\app\models\Country::find()->all(), 'name', 'name'),
        'theme' => Select2::THEME_BOOTSTRAP,
        'options' => ['placeholder' => 'Выберите страну', 'multiple' => true, 'autocomplete' => 'off'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]) ?>

    <?= $form->field($model, 'hours')->widget(TouchSpin::class, [
        'pluginOptions' => [
            'verticalbuttons' => true,
            'min' => 0,
            'max' => 23,
        ],
    ]) ?>

    <?= $form->field($model, 'minutes')->widget(TouchSpin::class, [
        'pluginOptions' => [
            'verticalbuttons' => true,
            'min' => 0,
            'max' => 59,
        ],
    ]) ?>

    <?= $form->field($model, 'director')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'actors')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'release_date')->widget(DatePicker::class, [
        'name' => 'release_date',
        'type' => DatePicker::TYPE_COMPONENT_APPEND,
        'readonly' => true,
        'pluginOptions' => [
            'todayHighlight' => true,
            'format' => 'yyyy-mm-dd',
            'autoclose' => true
        ]
    ]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'status')->dropDownList([
        '0' => 'Скоро в прокате',
        '1' => 'В прокате',
        '2' => 'Завершен'
    ]) ?>

    <?= $form->field($model, 'poster')->widget(FileInput::class, [
        'options' => ['accept' => 'image/*'],
        'pluginOptions' => [
            'initialPreview' => $isUpdate ? $model->getPosterUrl() : '',
            'initialPreviewAsData' => true,
            'showUpload' => false,
            'allowedFileTypes' => ['image']
        ],
    ]) ?>

    <?= $form->field($model, 'movie_shots[]')->widget(FileInput::class, [
        'options' => [
            'multiple' => true,
            'accept' => 'image/*'
        ],
        'pluginOptions' => [
            'initialPreview' => $isUpdate ? $model->getMovieShotsUrl() : [],
            'initialPreviewAsData' => true,
            'initialPreviewConfig' => $isUpdate ? $model->getPreviewConfig() : [],
            'overwriteInitial' => false,
            'showUpload' => false,
            'deleteUrl' => \yii\helpers\Url::to(['movie/delete']),
            'allowedFileTypes' => ['image']
        ],
    ]) ?>

    <?= $form->field($model, 'trailer')->widget(FileInput::class, [
        'options' => ['accept' => 'video/*'],
        'pluginOptions' => [
            'initialPreview' => $isUpdate ? $model->getTrailerUrl() : '',
            'initialPreviewFileType'=> 'video',
            'initialPreviewAsData' => true,
            'initialPreviewConfig'=> [
                ['filetype'=> "video/mp4"],
                ['caption'=> $model->name ? $model->name : '']
            ],
            'allowedFileTypes' => ['video'],
            'allowedFileExtensions'=>['mp4'],
            'showUpload' => false
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/movie/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Movie */

$this->title = 'Новый фильм';
$this->params['breadcrumbs'][] = ['label' => 'Фильмы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="movie-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/movie/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use kartik\date\DatePicker;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\MovieSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Фильмы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="movie-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Добавить фильм', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(['id' => 'movies', 'enablePushState' => false]); ?>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'id',
                'name',
                'genre',
                'country',
                'duration',
                [
                    'attribute' => 'release_date',
                    'value' => function ($movie) {

                        return Yii::$app->formatter->asDate($movie->release_date, 'dd/MM/yyyy');
                    },
                    'filter' => DatePicker::widget([
                        'model' => $searchModel,
                        'readonly' => true,
                        'attribute' => 'release_date',
                        'type' => DatePicker::TYPE_COMPONENT_APPEND,
                        'pluginOptions' => [
                            'autoclose' => true,
                            'format' => 'yyyy-mm-dd',
                            'todayHighlight' => true,
                        ]
                    ]),
                ],
                [
                    'attribute' => 'status',
                    'value' => function ($show) {
                        if ($show->status == 0) {
                            return 'Скоро в прокате';
                        } elseif ($show->status == 1) {
                            return 'В прокате';
                        }
                        return 'Прокат завершен';
                    },
                    'filter' => Html::activeDropDownList(
                        $searchModel,
                        'status',
                        [
                            '0' => 'Скоро в прокате',
                            '1' => 'В прокате',
                            '2' => 'Прокат завершен'
                        ],
                        [
                            'class' => 'form-control',
                            'prompt' => 'Выбрать'
                        ]
                    ),
                    'headerOptions' => ['width' => '140'],
                ],

                [
                    'class' => 'yii\grid\ActionColumn',
                    'header' => 'Действия',
                    'template' => '{view} &nbsp {update}',
                    'headerOptions' => ['width' => '80'],
                ],
            ],
        ]); ?>

    <?php Pjax::end(); ?>

</div>

views/movie/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Movie */

$this->title = 'Редактирование: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Фильмы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="movie-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'isUpdate' => true
    ]) ?>

</div>

views/movie/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Movie */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Фильмы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="movie-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'genre',
            'country',
            'duration',
            'director',
            'actors',
            'release_date',
            'description:ntext',
            [
                'attribute' => 'status',
                'value' => function ($movie) {
                    if ($movie->status == 0) {
                        return 'Скоро в прокате';
                    } elseif ($movie->status == 1) {
                        return 'В прокате';
                    }
                    return 'Завершен';
                },
            ],
            [
                'label' => 'Постер',
                'value' => function ($movie) {
                    return Html::img("/{$movie->images_path}poster.jpg", ['width' => '200px']);
                },
                'format' => 'html',
            ],
            [
                'label' => 'Кадры из фильма',
                'value' => function ($movie) {
                    $path = $movie->images_path . 'movie_shots';
                    $images = \yii\helpers\FileHelper::findFiles($path);
                    $result = "";
                    foreach ($images as $image) {
                        $result .= "<img src=\"/$image\" style=\"width: 400px;\">";
                    }
                    return $result;
                },
                'format' => 'raw',
            ],
            [
                'label' => 'Трейлер',
                'value' => function ($movie) {
                    return '<video controls style="width: 400px;"><source src="/' . $movie->images_path . 'trailer.mp4" type="video/mp4"></video>';
                },
                'format' => 'raw',
            ]
        ],
    ]) ?>
</div>